#!/bin/bash
# OSPF LSA Type Analysis
# Shows actual LSA types in OSPF database with explanations
#
# This demonstrates:
# - Type 1 (Router LSA): Generated by all routers, area-local
# - Type 2 (Network LSA): Generated by DR, area-local
# - Type 3 (Summary LSA): Generated by ABR, inter-area
# - Type 5 (External LSA): Generated by ASBR, domain-wide

set -e

echo "=========================================="
echo "OSPF LSA Type Analysis"
echo "=========================================="
echo ""
echo "This shows actual LSA types in the OSPF database"
echo ""

# Check if Docker FRR is running
if ! docker ps | grep -q frr-router; then
    echo "ERROR: Docker FRR setup not running"
    echo "Run: sudo ./setup_frr_docker.sh first"
    exit 1
fi

echo "[1/4] OSPF Database (all LSA types)"
echo "--------------------------------------------------------"
echo ""
echo "Router 1 LSDB:"
docker exec frr-router1 vtysh -c 'show ip ospf database' 2>/dev/null || echo "  (No database)"
echo ""

echo "[2/4] LSA Type Breakdown"
echo "--------------------------------------------------------"
echo ""
echo "Type 1 (Router LSA):"
docker exec frr-router1 vtysh -c 'show ip ospf database router' 2>/dev/null | head -20 || echo "  (No Type 1 LSAs)"
echo ""

echo "Type 2 (Network LSA):"
docker exec frr-router1 vtysh -c 'show ip ospf database network' 2>/dev/null | head -20 || echo "  (No Type 2 LSAs)"
echo ""

echo "Type 3 (Summary LSA):"
docker exec frr-router1 vtysh -c 'show ip ospf database summary' 2>/dev/null | head -20 || echo "  (No Type 3 LSAs - no multi-area setup)"
echo ""

echo "Type 5 (External LSA):"
docker exec frr-router1 vtysh -c 'show ip ospf database external' 2>/dev/null | head -20 || echo "  (No Type 5 LSAs - no ASBR configured)"
echo ""

echo "[3/4] LSA Type Explanations"
echo "--------------------------------------------------------"
echo ""
echo "Type 1 (Router LSA):"
echo "  - Generated by: All routers"
echo "  - Scope: Area-local (flooded within area only)"
echo "  - Contains: Router's links, interface costs, neighbor information"
echo "  - Example: Router 1.1.1.1 advertises its links to 10.1.1.0/24"
echo ""

echo "Type 2 (Network LSA):"
echo "  - Generated by: Designated Router (DR)"
echo "  - Scope: Area-local (flooded within area only)"
echo "  - Contains: Network segment information, attached routers"
echo "  - Example: DR advertises broadcast network 10.1.1.0/24 with attached routers"
echo ""

echo "Type 3 (Summary LSA):"
echo "  - Generated by: Area Border Router (ABR)"
echo "  - Scope: Inter-area (flooded between areas)"
echo "  - Contains: Routes from one area advertised to another"
echo "  - Example: ABR advertises 10.1.2.0/24 from Area 1 to Area 0"
echo ""

echo "Type 5 (External LSA):"
echo "  - Generated by: Autonomous System Boundary Router (ASBR)"
echo "  - Scope: OSPF domain-wide (flooded throughout domain)"
echo "  - Contains: External routes (from other routing protocols)"
echo "  - Example: ASBR advertises 192.168.1.0/24 learned from BGP"
echo ""

echo "[4/4] NRS-1/NRS-2 Exam Notes"
echo "--------------------------------------------------------"
echo ""
echo "Key Points:"
echo "  - Type 1: All routers generate, area-local"
echo "  - Type 2: DR generates, area-local"
echo "  - Type 3: ABR generates, inter-area"
echo "  - Type 5: ASBR generates, domain-wide"
echo ""
echo "Flooding Scope:"
echo "  - Type 1 & 2: Within area only"
echo "  - Type 3: Between areas (via ABR)"
echo "  - Type 5: Throughout entire OSPF domain"
echo ""
echo "Area Behavior:"
echo "  - Stub area: No Type 5 LSAs, default route injected"
echo "  - NSSA: Allows Type 7 LSAs (converted to Type 5 by ABR)"
echo "  - Backbone (Area 0.0.0.0): Required, connects all areas"
echo ""

echo "=========================================="
echo "Analysis Complete"
echo "=========================================="

